Add search component
piotrekpasciak/the-rickest-rick pull request #3
Opened 2018-12-08 22:31 UTC by piotrekpasciak

2018-12-09 10:15 UTC, mpawlowska requested changes

2018-12-09 10:15 UTC, mpawlowska commented on src/views/Home.vue
> +    },
What about creating one generic method for getting episodes and use it: in `created` hook, in `debounceSearchInput` and for getting additional episodes? That way you will save some recurring code and the component becomes cleaner. But to use such an universal method, you'll have to think about make it more 'elastic', for example while setting `this.currentPage`, and while setting `this.episodes`. Also, to use it in `debounceSearchOnInput`, you will have to do some additional things in this method, before calling `this.getEpisodesHandler` (eg. setting current page to proper value).

2018-12-09 10:15 UTC, mpawlowska commented on src/components/GenericEpisodeItem.vue
> +      getSeasonNumber() {
for `computed` options it's a good idea to use names without verbs (as in `data` property`), so for example here it could be `seasonNumber`

2018-12-09 10:15 UTC, mpawlowska commented on src/views/Home.vue
> +      <input v-model="currentQuery" @input="debounceSearchOnInput()" type="text" placeholder="Search">
it's not neccessary to use `()` @input event --> you can simply write `@input="debounceSearchOnInput"`

2018-12-11 22:33 UTC, piotrekpasciak commented on src/components/GenericEpisodeItem.vue
> +      }
I don't really get it. It's already calculated inside of computed block.

2018-12-12 20:49 UTC, mpawlowska commented on src/components/GenericEpisodeItem.vue
> +      }
My bad :) You're right.
BTW I don't know if you spotted that, but I sent you a link on Slack to repo with ready app

2018-12-12 20:55 UTC, piotrekpasciak commented on src/components/GenericEpisodeItem.vue
> +      }
I've seen the link but i didn't want to cheat. I think I'll finish app by myself and then compare the solution.

2018-12-13 08:02 UTC, mpawlowska commented on src/components/GenericEpisodeItem.vue
> +      }
That's great! :)

2020-09-08 09:44 UTC, merged